title: The Routing Loop
description: Weekly AWS Networking Twitch Show
url: "" # leave empty for local development, set to your production URL when deploying
baseurl: "" # subpath of your site, e.g. /blog

color-scheme: "mediumseagreen" # the scheme can be any HEX code like "#00aa55"

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache

future: true

google_analytics: G-2K7T1C764L